name: Sync Go Dependencies

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday 6AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          echo "PWD: $(pwd)"
          echo "Files:"
          ls -al
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          ls -R $GITHUB_WORKSPACE
      - name: Run Shared Go Dependency Sync
        uses: sunil-kumar-h/shared-go-sync-action@main
        with:
          shared-mod-url: "https://raw.githubusercontent.com/sunil-kumar-h/shared-deps/refs/heads/main/go.mod"
          github-token: ${{ secrets.MY_PAT }}
          repo-owner: sunil-kumar-h
          repo-name: ${{ github.event.repository.name }}
          folder-path: "go-sample-proj"
          ignore-file: "${{ github.workspace }}/.depignore"
